"""initial schema

Revision ID: 986baf76c7f6
Revises:
Create Date: 2026-09-06 12:59:11.407244
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "986baf76c7f6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovery_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("config_version", sa.String(length=40), nullable=False),
        sa.Column("discovered_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_key", sa.String(length=255), nullable=False),
        sa.Column("task_name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_key"),
    )
    op.create_index(op.f("ix_job_runs_task_name"), "job_runs", ["task_name"], unique=False)
    op.create_table(
        "ranking_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("period_days", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("baseline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint("period_days IN (7, 14, 30)", name="ck_ranking_period"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("period_days", "as_of", "config_version", name="uq_ranking_run"),
    )
    op.create_index(op.f("ix_ranking_runs_as_of"), "ranking_runs", ["as_of"], unique=False)
    op.create_index(
        op.f("ix_ranking_runs_period_days"), "ranking_runs", ["period_days"], unique=False
    )
    op.create_table(
        "repositories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("github_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("owner", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("html_url", sa.String(length=500), nullable=False),
        sa.Column("language", sa.String(length=80), nullable=True),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("license_name", sa.String(length=120), nullable=True),
        sa.Column("stars_count", sa.Integer(), nullable=False),
        sa.Column("forks_count", sa.Integer(), nullable=False),
        sa.Column("open_issues_count", sa.Integer(), nullable=False),
        sa.Column("is_fork", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("pushed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("github_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_tracked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("history_available_from", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_repositories_full_name"), "repositories", ["full_name"], unique=True)
    op.create_index(op.f("ix_repositories_github_id"), "repositories", ["github_id"], unique=True)
    op.create_index(op.f("ix_repositories_language"), "repositories", ["language"], unique=False)
    op.create_index(op.f("ix_repositories_owner"), "repositories", ["owner"], unique=False)
    op.create_index(
        "ix_repository_active_language", "repositories", ["archived", "language"], unique=False
    )
    op.create_table(
        "ranking_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ranking_run_id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("previous_rank", sa.Integer(), nullable=True),
        sa.Column("start_stars", sa.Integer(), nullable=False),
        sa.Column("end_stars", sa.Integer(), nullable=False),
        sa.Column("net_delta", sa.Integer(), nullable=False),
        sa.Column("growth_rate", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["ranking_run_id"], ["ranking_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ranking_run_id", "rank", name="uq_ranking_position"),
        sa.UniqueConstraint("ranking_run_id", "repository_id", name="uq_ranking_repo"),
    )
    op.create_index(
        op.f("ix_ranking_items_net_delta"), "ranking_items", ["net_delta"], unique=False
    )
    op.create_index(
        op.f("ix_ranking_items_ranking_run_id"), "ranking_items", ["ranking_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_ranking_items_repository_id"), "ranking_items", ["repository_id"], unique=False
    )
    op.create_table(
        "repo_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stars_count", sa.Integer(), nullable=False),
        sa.Column("forks_count", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "snapshot_date", name="uq_repo_snapshot_date"),
    )
    op.create_index(
        op.f("ix_repo_snapshots_repository_id"), "repo_snapshots", ["repository_id"], unique=False
    )
    op.create_index(
        op.f("ix_repo_snapshots_snapshot_date"), "repo_snapshots", ["snapshot_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_repo_snapshots_snapshot_date"), table_name="repo_snapshots")
    op.drop_index(op.f("ix_repo_snapshots_repository_id"), table_name="repo_snapshots")
    op.drop_table("repo_snapshots")
    op.drop_index(op.f("ix_ranking_items_repository_id"), table_name="ranking_items")
    op.drop_index(op.f("ix_ranking_items_ranking_run_id"), table_name="ranking_items")
    op.drop_index(op.f("ix_ranking_items_net_delta"), table_name="ranking_items")
    op.drop_table("ranking_items")
    op.drop_index("ix_repository_active_language", table_name="repositories")
    op.drop_index(op.f("ix_repositories_owner"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_language"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_github_id"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_full_name"), table_name="repositories")
    op.drop_table("repositories")
    op.drop_index(op.f("ix_ranking_runs_period_days"), table_name="ranking_runs")
    op.drop_index(op.f("ix_ranking_runs_as_of"), table_name="ranking_runs")
    op.drop_table("ranking_runs")
    op.drop_index(op.f("ix_job_runs_task_name"), table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_table("discovery_runs")
    # ### end Alembic commands ###
