/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rankings */
        get: operations["list_rankings_api_v1_rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repos/{owner}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repository */
        get: operations["get_repository_api_v1_repos__owner___name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repos/{owner}/{name}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repository Snapshots */
        get: operations["get_repository_snapshots_api_v1_repos__owner___name__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Filters */
        get: operations["get_filters_api_v1_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FilterOption */
        FilterOption: {
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** FilterResponse */
        FilterResponse: {
            /** Languages */
            languages: components["schemas"]["FilterOption"][];
            /** Topics */
            topics: components["schemas"]["FilterOption"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Service */
            service: string;
        };
        /**
         * PeriodDays
         * @enum {integer}
         */
        PeriodDays: 1 | 7 | 14 | 30;
        /** RankingItemResponse */
        RankingItemResponse: {
            /** Rank */
            rank: number;
            /** Previous Rank */
            previous_rank?: number | null;
            /** Full Name */
            full_name: string;
            /** Owner */
            owner: string;
            owner_github_id?: number | null;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Language */
            language: string | null;
            /** Topics */
            topics: string[];
            /** Total Stars */
            total_stars: number;
            /** Star Delta */
            star_delta: number;
            /** Growth Rate */
            growth_rate: number | null;
            /** Baseline Available */
            baseline_available: boolean;
            /** Last Updated At */
            last_updated_at: string | null;
            /** Github Url */
            github_url: string;
        };
        /** RankingMeta */
        RankingMeta: {
            period_days: components["schemas"]["PeriodDays"];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Baseline At */
            baseline_at: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Coverage */
            coverage: number;
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "demo" | "live";
        };
        /** RankingResponse */
        RankingResponse: {
            /** Data */
            data: components["schemas"]["RankingItemResponse"][];
            meta: components["schemas"]["RankingMeta"];
        };
        /** RepositoryResponse */
        RepositoryResponse: {
            /** Full Name */
            full_name: string;
            /** Owner */
            owner: string;
            owner_github_id?: number | null;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Html Url */
            html_url: string;
            /** Language */
            language: string | null;
            /** Topics */
            topics: string[];
            /** License Name */
            license_name: string | null;
            /** Stars Count */
            stars_count: number;
            /** Forks Count */
            forks_count: number;
            /** Open Issues Count */
            open_issues_count: number;
            /** Pushed At */
            pushed_at: string | null;
            /** Github Created At */
            github_created_at: string | null;
            /**
             * First Tracked At
             * Format: date-time
             */
            first_tracked_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /**
             * History Available From
             * Format: date-time
             */
            history_available_from: string;
        };
        /** SnapshotResponse */
        SnapshotResponse: {
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Stars Count */
            stars_count: number;
            /** Forks Count */
            forks_count: number;
        };
        /** SnapshotSeriesResponse */
        SnapshotSeriesResponse: {
            /** Repository */
            repository: string;
            /**
             * Range
             * @enum {string}
             */
            range: "30d" | "90d" | "365d";
            /** Data */
            data: components["schemas"]["SnapshotResponse"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_rankings_api_v1_rankings_get: {
        parameters: {
            query?: {
                period?: components["schemas"]["PeriodDays"];
                language?: string | null;
                topic?: string | null;
                minStars?: number;
                q?: string | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repository_api_v1_repos__owner___name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repository_snapshots_api_v1_repos__owner___name__snapshots_get: {
        parameters: {
            query?: {
                range?: "30d" | "90d" | "365d";
            };
            header?: never;
            path: {
                owner: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filters_api_v1_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
